name: llvm-builder
on: [push]

env:
  LLVM_TAG: llvmorg-15.0.6
  LLVM_DEB: llvm.deb
  install_dir: ${{ github.path }}/llvm-root

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          key: ccache
          path: |
            .cache
            llvm-project
      - run: |
          [ -e llvm-project ] \
            && (cd llvm-project && git pull --rebase && git checkout ${LLVM_TAG} && git submodule update --init) \
            || (git clone -b ${LLVM_TAG} https://github.com/llvm/llvm-project.git && cd llvm-project && git submodule update --init)
      - name: Build
        run: |
          ./build.sh
          mkdir -p ${install_dir}/DEBIAN
          cp control ${install_dir}/DEBIAN/
          dpkg-deb -b ${install_dir} ${LLVM_DEB}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: llvm
          path: ${{ env.install_dir }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.install_dir }}
            ${{ env.LLVM_DEB }}

