name: llvm-builder
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      llvm_tag: main
      pkg: llvm-main
      install_dir: llvm-root
      cache_dir: .cache
    steps:
      - run: |
          curl -L https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
      - run: |
          sudo apt update
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt install -y g++-11 build-essential ninja-build ccache wget python3 python3-dev python3-pip unzip
          sudo python3 -m pip install numpy pybind11
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          key: ccache-${{ env.llvm_tag }}
          path: |
            ${{ env.cache_dir }}
            llvm-project
      - run: |
          [[ ! -e llvm-project ]] && git clone https://github.com/llvm/llvm-project.git
          cd llvm-project
          git checkout ${llvm_tag}
          git submodule update --init
      - name: Build
        run: |
          INSTALL_DIR=$PWD/$install_dir CACHE_DIR=$PWD/$cache_dir ./build.sh
          tar -czf ${{ env.pkg}}.tar.gz $install_dir
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.pkg }}.tar.gz

